### ISSUE TITLE
Implement LaserScan conversion capability

### ISSUE THREAD

**Issue by janapavlasek** [mcgill-robotics/ros-tritech-micron#1]
Must be able to set a flag on launch of node that will have the package publish a `LaserScan` instead of a `PointCloud`.

**Comment by anassinator** [comment]
This sort of processing is lossy and there is no expected/correct/defined way for this to be implemented. So I suggest this be part of a separate package in order to avoid complexity. Simply a sonar_proc package with a to_lasercan node should do.

**Comment by janapavlasek** [comment]
Makes sense, I will open an issue on the `auv
