### ISSUE TITLE
Head_inf reversed

### ISSUE THREAD

**Issue by sousapedro596** [mcgill-robotics/ros-tritech-micron#2]
This is one excerpt of the Tritech's documentation: (pag 27) 

> Bits 6,7 Operation
If the Surface Controller is just taking control of the subsea device it must first ensure that the device has a Parameter set before it can start issuing mtSendData requests. Bits 6 and 7 should be read to determine if the Sonar has received a validated set of parameters from the surface controller (i.e. it has received a valid ‘mtHeadCommand’).
Bit 6 will be set to 1 if the device has No Parameters. If this is the case then an 'mtHeadCommand'
message must be sent to the subsea device to upload the parameters to it. If Bit 6 is set to 0 then this will indicate that the device already Has Parameters. If the User program is just taking control of the subsea device then it would be advised at this stage to perform a hardware Stop and Reset. This is performed by sending an 'mtReBoot' command to the device which will clear the parameter block. The 'mtHeadCommand' should then be sent which will include a full set of known parameters.
Bit 7 will indicate whether the Sonar has yet sent an mtBBUserData reply (in response to an
mtSendBBUser request) since the Sonar was powered up and/or rebooted.
**Bit 7 should be used as acknowledgement that the head has sent an mtBBUserData reply.** Bit 6 should then be checked until it is set to 0 to indicate a validation of the received Parameters sent in the mtHeadCommand. The surface controller can then issue mtSendData requests once Bit 7 is 1 and Bit 6 is 0.

**Bit 7 should be used as acknowledgement that the head has sent an mtBBUserData reply.**

Since the message 'mtBBUserData' is not sent I assumed there's no way of the flag `self.has_cfg = head_inf[7]` become True... It simply work because the opposed bits if we consider bits 7, 6 to be bits 0, 1 the RECENTERING and CENTERED them could easily became True and False like the self.has_cfg and self.no_params need...  This is my explanation for now, and it makes some sense because if we read the byte in the reverse order RECENTERING and CENTERED are always different as we would expect (at least as far as what I have see during runtime...)

It's not a perfect explanation, but I have been developing a driver for another sensor from Tritech, a Sub Bottom Profiller and I lost some time debugging why when I send the 'mtHeadCommand' the flag head_inf[7] which is No_Params keeps True, and the opposed, bit 1, always change when I send 'mtHeadCommand'... If I read the byte reversed it simply works by ignoring **has_cfg** which cannot change since we don't send 'SendBBUser'.

For now, I reversed the byte in the two drivers and it works fine if I check only the NO_PARAMS bit... (without 'SendBBUser')

Of course, take this with a grain of salt but what you think? Did I miss something?

**Comment by anassinator** [comment]
Interesting. There was always a problem there on our end, but repeated `REBOOT` commands seem to eventually fix it. In other words, both `has_config` and `no_params` get properly set after a while. 

When you try to run this as is, are you stuck in an infinite loop [here](https://github.com/mcgill-robotics/ros-tritech-micron/blob/master/src/tritech_micron/sonar.py#L151-L157)?

I'll try your fork when I get the chance, to see if it still works on the Micron.

**Comment by sousapedro596** [comment]
Ok, about `has_cfg` I think that without we send `BBUserData` message it cannot change to `True`.

If I reverse the byte, yes I keep stuck in the loop, but for now I ignored `has_cfg` and everything seems fine. 

About the `head_inf` I think that byte shloud be read as litle endian...

About `mtHeadData` fails at the start and sometimes when reconfiguring we need to add extra checks (added that in my last commit, check if motor is stopped and if it is centered) but it not prevent the `mtHeadData` fail when I invert the motor direction using dynamic reconfigure, which makes sense since there aren't implemented checks to see if after a motor direction change we wait for motor to be centered and stopped. 

Right now, in my forked version, dynamic reconfigure don't reconfigure at the start (added a extra flag, not perfect but works...), `mtHeadData` doesn't fail at the beginning and also doesn't fail with synamic reconfigure as long as we don't invert the motor direction. This was tested in Tritech Micron DST

**Comment by sousapedro596** [comment]
> When you try to run this as is, are you stuck in an infinite loop here?
Yes, with your version, when applied to the other sensor which don't have motor the byte never changes.

**Comment by anassinator** [comment]
Sorry for taking so long.

Unfortunately, I've not been able to replicate the issue on our system. 
I consistently get the following output, with `HEAD_DATA` timeouts
<img width="1680" alt="screen shot 2016-02-14 at 01 34 23" src="https://cloud.githubusercontent.com/assets/723610/13037765/280fa6e8-d356-11e5-8b60-0b6c8172ce72.png">
but it eventually works without needing to change any of the `head_inf` bits as such:
<img width="1680" alt="screen shot 2016-02-14 at 01 34 25" src="https://cloud.githubusercontent.com/assets/723610/13037781/63d6b568-d356-11e5-8e16-6735552e8c0b.png">
In other words, `has_cfg` does eventually become `true`. Of course, this isn't ideal, but I believe this is properly implementing the SeaNet protocol as defined on page 2 of their documentation:
<img width="508" alt="screen shot 2016-02-14 at 20 11 08" src="https://cloud.githubusercontent.com/assets/723610/13037832/45324518-d357-11e5-9edd-d815a64669e0.png">
and on page 27:
<img width="901" alt="screen shot 2016-02-14 at 20 16 40" src="https://cloud.githubusercontent.com/assets/723610/13037864/f9f72784-d357-11e5-8685-bcdb6215310d.png">

Maybe bit 7 (`has_cfg`) is never supposed to be set, but it was for me. And ignoring that bit did not have an effect after all. Bit 6 (`no_params`) is really the one that we're waiting for here and is causing the numerous retries. On the other hand, if I invert the bit as you said, then I get stuck in an infinite loop. So I do not believe it should be read as such.

Could you detail the exact configuration you're sending and how? Step by step instructions on how to replicate the issue would be appreciated!

**Comment by anassinator** [comment]
@sousapedro596 Is this still an issue?

**Comment by anassinator** [comment]
@sousapedro596 I'm closing this for now. Feel free to re-open it when you're ready.
