### ISSUE TITLE
Query regarding the source of commands used in the drivers

### ISSUE THREAD

**Issue by asgv123** [mcgill-robotics/ros-tritech-micron#7]
Hi!
I am a member of the software sub-division of AUV-IITB, a tech team at IIT Bombay. We are currently working on integrating a sonar - Tritech Super SeaKing - into our system, which primarily runs on Ubuntu.

We have been unable to locate any resource to help us write drivers for the same in Ubuntu. Can you please provide some library or documentation to help us?

If not, can you at least provide the sources used to write the commands and obtain the libraries used in your code for Sea Micron.

Any help is appreciated.

Thanks
Andrews GV
Software Trainee
AUV-IITB

**Comment by anassinator** [comment]
@asgv123 Sorry for the delay! We got the documentation straight from Tritech and attaching them below.
As for Ubuntu support, this library should just work along with ROS. The code in `src/tritech_micron` should also work standalone without any ROS integration.

[Decoding Sonar Scanline Data.PDF](https://github.com/mcgill-robotics/ros-tritech-micron/files/3998644/Decoding.Sonar.Scanline.Data.PDF)
[SeaNet_DigSon_Protocol.pdf](https://github.com/mcgill-robotics/ros-tritech-micron/files/3998645/SeaNet_DigSon_Protocol.pdf)

**Comment by asgv123** [comment]
Ok. Thanks a lot for the help!
